### ISSUE TITLE
Reloads the page twice on rebuild

### ISSUE THREAD

**Issue by Gama11** [varomix/mixliveserver#3]
I was testing this extension for Flixel projects (using the standard Mode demo). It works fine, apart from reloading the page _twice_ after each recompilation (`lime build html5`).

![](http://i.imgur.com/0Cv3QXj.gif)

If you do `lime build html5` followed by a `lime build html5 -debug`, you'll notice that after the second compilation, the first time it reloads the game from the previous compilation (with `-debug`, the Flixel splash screen does not appear).

**Comment by varomix** [comment]
maybe some file still changes after a few seconds, cause the server reloads when it detects a change in the files, there might be an option to not update as soon

**Comment by varomix** [comment]
Workaround for now, disable the splash screen
like this in the Main.hx
```haxe
class Main extends Sprite
{
	public function new()
	{
		super();
		addChild(new FlxGame(0, 0, PlayState, null,null,null,true));
	}
}
````

**Comment by varomix** [comment]
Seems to be a Flixel related issue, use workaround  to disable splash screen

**Comment by Gama11** [comment]
That is ... very strange. I have the feeling this would happen with more than just Flixel.

**Comment by varomix** [comment]
well disabling the splash screen works and never had any issue while working with Kha

**Comment by Gama11** [comment]
That may very well be the case, but it seems more like a symptom rather than the real issue. Maybe OpenFL or Lime just does something a little bit different under the hood that causes this (and would cause it for other engines doing the same thing too).

Anyway, thanks for letting me know, that's already helpful to know that it doesn't happen with Kha / has to do with the Splash screen specifically. :) Will try to look into it more closely sometime.

**Comment by varomix** [comment]
maybe Flixel still touches a file after a few secs as I said, that would trigger a reload
