### ISSUE TITLE
Page doesn't open if there's no open file

### ISSUE THREAD

**Issue by Gama11** [varomix/mixliveserver#4]
If you run the "Start live server command" with no other tabs open, nothing happens.

Looking at the debug console, there is a warning about this:

>Cannot execute mixliveserver.open because there is no active text editor.

However, that's quite hidden and the average user probably doesn't think to look there. I think it would be better to use one of those popup messages instead (`vscode.window.showErrorMessage(text);`).

Alternatively, if would of course be even better if you could find a solution / workaround.

**Comment by varomix** [comment]
Yeah, the command wants to SPLIT the current tab so a tab should be open

**Comment by Gama11** [comment]
Could it check whether there's a tab currently and then open a tab instead of splitting it?

**Comment by varomix** [comment]
I have to check depends on what the electron API can do :)

**Comment by varomix** [comment]
need to have a file open, makes no sense to not have a source file open since you want to see the result of that code
